# To create status badge per os, python-version, and torch-version, we use workflow call.
# https://github.com/orgs/community/discussions/52616

# TODO: coverage

name: Tests for package as workflow call

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      torch-version:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  package:
    name: Run package tests
    runs-on: ${{ inputs.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies (Windows)
        if: ${{ inputs.os == 'windows-latest' }}
        run: |
          powershell -File tests/scripts/install_windows_dependencies.ps1
      - name: Install dependencies (Ubuntu)
        if: ${{ inputs.os == 'ubuntu-latest' }}
        run: |
          . tests/scripts/free_ubuntu_disk.sh
          . tests/scripts/install_ubuntu_dependencies.sh
      - name: Install dependencies (MacOS)
        if: ${{ inputs.os == 'macos-15-intel' || inputs.os == 'macos-latest' }}
        run: |
          . tests/scripts/install_macos_dependencies.sh
      - name: Show version of FFmpeg
        run: |
          ffmpeg -version
      - name: Overwrite torch version in pyproject.toml
        shell: bash
        env:
          PYTHON_VERSION: ${{ inputs.python-version }}
          TORCH_VERSION: ${{ inputs.torch-version }}
        run: |
          uv venv --python ${PYTHON_VERSION}

          if [ "${RUNNER_OS}" = "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi

          uv pip install packaging
          python tests/scripts/overwrite_pyproject_toml.py --path pyproject.toml --torch-version ${TORCH_VERSION}
      - name: Install dependencies
        shell: bash
        run: |
          if [ "${RUNNER_OS}" = "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi

          uv pip install -e ".[dev,tests]"

          if [ "${RUNNER_OS}" = "Windows" ]; then
            uv pip install soundfile
          fi
      - name: Install torchcodec
        shell: bash
        run: |
          if [ "${RUNNER_OS}" = "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi

          python tests/scripts/overwrite_torchcodec_requirement.py \
            --path requirements-torchcodec.txt

          uv pip install -r requirements-torchcodec.txt
      - name: Show dependencies
        shell: bash
        run: |
          if [ "${RUNNER_OS}" = "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi

          uv pip list
      - name: Verify version of torch
        shell: bash
        env:
          TORCH_VERSION: ${{ inputs.torch-version }}
        run: |
          if [ "${RUNNER_OS}" = "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi

          python tests/scripts/verify_torch_version.py --torch-version "${TORCH_VERSION}"
      - name: Run package tests
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MPLBACKEND: AGG
          USE_LIBUV: 0
        run: |
          PYTEST_FLAGS="--log-cli-level=ERROR --cov=audyn/ --cov-report=xml"

          if [[ "${{ github.head_ref }}" == release/* ]]; then
            PYTEST_FLAGS="${PYTEST_FLAGS} --runslow"
          fi

          if [ "${RUNNER_OS}" = "Windows" ]; then
            PYTEST_FLAGS="${PYTEST_FLAGS} -p no:faulthandler"
          fi

          if [ "${RUNNER_OS}" = "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi

          uv run --active pytest -vvv ${PYTEST_FLAGS} tests/package/
